# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_MEMORY = 24576
VM_CPUS = 8
VM_DISK = 150

Vagrant.configure("2") do |config|
  # Project: https://github.com/alvistack/vagrant-rhel
  config.vm.box = "cloud-image/ubuntu-24.04"
  config.vm.hostname = "u24"
  config.ssh.forward_agent = true
  config.vm.define "u24_ovn"

  # Network
  config.vm.network "private_network", ip: "192.168.20.10", auto_config: false 
  config.vm.network "private_network", ip: "192.168.30.10", auto_config: false

  # Libvirt specific configuration
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = VM_MEMORY
    libvirt.cpus = VM_CPUS
    libvirt.nested = true
    libvirt.machine_virtual_size = VM_DISK
    libvirt.qemu_use_session = false
  end

  # Preprovisioning with shell script
  #config.vm.provision "shell", inline: "sudo apt update; sudo apt -y install python3"

  # Provisioning with a ansible.
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/openstack/provisioning.yaml"
      ansible.ask_vault_pass = false
      ansible.extra_vars = {
        devstack_user: "stack",
        devstack_password: "stack",
        iface1: "ens5",
        iface2: "ens6",
        iface3: "ens7",
        devstack_base_dir: "/opt/stack",
      }
  end

end
