# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_MEMORY = 24576
VM_CPUS = 8
VM_DISK = 150
VM_NUM = 4

Vagrant.configure("2") do |config|
  # Iterate from 1 to VM_NUM
  (1..VM_NUM).each do |idx|
    # Define each machine
    config.vm.define "u22#{idx}" do |node|
      # Project: https://github.com/alvistack/vagrant-rhel
      node.vm.box = "cloud-image/ubuntu-22.04"
      node.vm.hostname = "u22#{idx}"
      node.ssh.forward_agent = true
      node.vm.define "u22ovn#{idx}"
    
      # Network
      #config.vm.network "private_network", ip: "192.168.20.10"" 
    
      # Libvirt specific configuration
      node.vm.provider "libvirt" do |libvirt|
        libvirt.memory = VM_MEMORY
        libvirt.cpus = VM_CPUS
        libvirt.nested = true
        libvirt.machine_virtual_size = VM_DISK
        libvirt.qemu_use_session = false
      end
    
      # Preprovisioning with shell script
      node.vm.provision "shell", inline: "echo 'Configuring node-#{idx}'"
    
      # Provisioning with a ansible.
      node.vm.provision "ansible" do |ansible|
          ansible.playbook = "../ansible/openstack/provisioning.yaml"
          ansible.ask_vault_pass = false
          ansible.extra_vars = {
            devstack_user: "stack",
            devstack_password: "stack",
            iface1: "ens5",
            iface2: "ens6",
            iface3: "ens7",
            devstack_base_dir: "/opt/stack",
          }
      end
    end  # node
  end  # iter VM_NUM
end  # config
