# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_MEMORY = 24576
VM_CPUS = 8
VM_DISK = 150

Vagrant.configure("2") do |config|
  # Project: https://github.com/alvistack/vagrant-rhel
  config.vm.box = "alvistack/rhel-9"
  config.vm.hostname = "rhel9"
  config.ssh.forward_agent = true

  # Libvirt specific configuration
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = VM_MEMORY
    libvirt.cpus = VM_CPUS
    libvirt.nested = true
    libvirt.machine_virtual_size = VM_DISK
    libvirt.qemu_use_session = false
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
