# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_MEMORY = 16386
VM_CPUS = 4
VM_DISK = 50

Vagrant.configure("2") do |config|
  # https://github.com/alvistack/vagrant-centos/blob/master/Vagrantfile
  config.vm.hostname = "centos-10-stream"
  config.vm.box = "alvistack/centos-10-stream"
  config.vm.hostname = "cs10"
  config.ssh.forward_agent = true
  config.vm.define "cs10"

  # Network
  config.vm.network "private_network", ip: "192.168.20.10", auto_config: false 
  config.vm.network "private_network", ip: "192.168.30.10", auto_config: false

  # Libvirt specific configuration
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = VM_MEMORY
    libvirt.cpus = VM_CPUS
    libvirt.nested = true
    libvirt.machine_virtual_size = VM_DISK
    libvirt.qemu_use_session = false
  end

end
